### PR TITLE
Offload HostVNicDetail to NetAdapterWorkerPrepare, and fix #1

### LINKED ISSUE #1: HostVNicWorker shouldn't use Name to query VMNetworkAdapter instances.
Multiple vNics can have the same name, so this won't always work.

### PR DESCRIPTION
**Pull request by tmolenh**
Fix three bugs:
- HostVNIcs are queried twice (once by as a host vnic, and again by `NativeNicDetail`)
- Bug #1 
- Removed `Get-VMNetworkAdapterFailoverConfiguration` query for host vNICs because it only applies to VM NICs.

### CODE REVIEW

**Comment by omarcardona** [comment]
Hi Tom,

  *   It looks form this change that now the output is not saved in a named Host vNIC directory anymore.
  *   It's also not clear if the Host vNIC has both the NetAdapter and VMNIC sides of the device captured.
  *   Please confirm the before and after Get-NetView output still displays the named Host vNIC directory _AND_ contains both outputs highlighted below
     *   ***@***.***

**Comment by omarcardona** [comment]
*   In the After output below, the Host vNIC 11 Container name is dropped.
  *   How do we quickly distinguish usage?  For example, standard Host vNIC vs Container NICs?

**Comment by tmolenh** [comment]
Point still stands that "Container NIC abc" is just the naming convention HNS uses for its vNICs.

**Comment by tmolenh** [comment]
The name does not convene any additional information beyond stating it is attached to the Default Switch. Get-NetView makes this painfully clear, so I'm confused by your claim that it can expedite investigations. Especially when my experience has been exactly the opposite.

**Pull request merged**
